### ISSUE TITLE
ValueSet using CodeSystem supplement

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#37]
I'm not sure if it's good to define value sets as "include all from supplement".

"compose": {
    "include": [
      {
        "system": "https://fhir.ee/CodeSystem/abivahendid-ja-meditsiiniseadmed",
        "version": "4"
      }
    ],

I don't have strong evidence for this, but it felt a little unsafe.

**Comment by rlindstrm** [comment]
Just for discussion for now.

**Comment by rlindstrm** [comment]
https://chat.fhir.org/#narrow/stream/179202-terminology/topic/ValueSet.3A.20compose.2Einclude.20all.20from.20supplement.3F

Reply from that thread:

You certainly can define an explicit ValueSet that both:

- includes all codes from a code system (this is just compose.include.system =[CodeSystem URI], and
- references one or more supplements (use the http://hl7.org/fhir/StructureDefinition/valueset-supplement extension)

But, if the URI of this ValueSet is the same as the CodeSystem.valueSet URI, then it's possible (likely? / allowed? / expected? / required?) for the terminology server to NOT use the explicit ValueSet's definition and instead use the implicit definition of "all codes in the code system" NOT accounting for any supplements.

I believe that there is no current consensus on what the correct or preferred behaviour should be in this case.

**Comment by rlindstrm** [comment]
As it's not expanding in Ontoserver, I asked again:

I don’t believe your ValueSet definition is legal; the URL of a supplement cannot be used to identify a CodeSystem.
This is implied by:
The CodeSystem.url for a supplement SHALL never appear in a [Coding.system](https://www.hl7.org/fhir/R4/datatypes.html#Coding)
But also because ValueSet.compose.include.system  is “The system the codes come from”, but that system is SNOMED, not the supplement.


In order to define a ValueSet that matches just the codes from a supplement you’d need the supplement to add a property to the codes that you can then filter on with the ValueSet.compose

**Comment by rlindstrm** [comment]
ValueSets using CS supplements should be remade (either explicitly listing VS members or adding a property we could filter on in the CS supplement - not sure you can filter on random self-made property to be honest).

**Comment by marinaivnv** [comment]
ValueSets that are based on supplements are redefined: include specifies base CodeSystem and extension specifies supplement CodeSystem with Estonian translations. 

This ValueSets are: 
- abivahendid-ja-meditsiiniseadmed
- antibiootikumtundlikkus
- kehapiirkond
- kvalitatiivse-uuringu-vastus
- proovimaterjali-tyyp-meditsiinilaborites

In order to receive Estonian translations `displayLanguage=et` parameter should be used while $expand operation!

In two cases `abivahendid-ja-meditsiiniseadmed` and `proovimaterjali-tyyp-meditsiinilaborites` Onstoserver response with error (NullPointerException) on $expand operation call. Error is caused by property "parent". I think it should be a bug, will investigate it with Michael Lawley.

**Comment by rlindstrm** [comment]
Please include the display labels from CS supplement in the ValueSet definition, otherwise Ontoserver would not know which designations to use, and would choose preferred terms of SNOMED, not the terms specified in the CS supplement. displayLanguage=et would only query preferred terms, not the actual terms what we've chosen for the ValueSet.

**Comment by marinaivnv** [comment]
Display labels from CS supplement are now included in the ValueSet definition.
