### ISSUE TITLE
HL7 value sets

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#46]
A few more value sets have been identified as HL7 value sets: the list is in sheet "HL7" in the [big table](https://docs.google.com/spreadsheets/d/1GJ0d924TWQCWlQj1UN8c-NiFa9BM55ykfOBwIN3OAW8/edit#gid=564345510).

They need code system supplements for translations. In big table, these value sets have been marked with status 2 or 6 (6 for those, that have been already imported as local code systems).

**Comment by marinaivnv** [comment]
Import of HL7 code systems was done directly to Ontoserver (without TermX).

Need to mention that some CS have English translations instead of Estonian:

- paringu-staatus: https://raw.githubusercontent.com/TEHIK-EE/terminology-migration/main/pubkeskus/pub-data/files/10468.csv 
- paringu-vastuse-kood: https://raw.githubusercontent.com/TEHIK-EE/terminology-migration/main/pubkeskus/pub-data/files/10472.csv

In order to receive Estonian translations displayLanguage=et parameter should be used while $expand operation!

**Comment by marinaivnv** [comment]
ActCode CodeSystem has errors on the HL7 side. Fixed CS definition is here:
[CodeSystem-v3-ActCode.json](https://github.com/TEHIK-EE/terminology-migration/files/14535282/CodeSystem-v3-ActCode.json)
